### ISSUE TITLE
Unhandled Exception: System.Xml.XmlException

### ISSUE THREAD

**Issue by doubley612** [FalconForceTeam/SOAPHound#3]
Thank you for this tool :)

When I want to dump bh using this command

`SOAPHound.exe  -c C:\Users\USER\Downloads\SOAPHound-main\bin\Release\soaphound_cache.txt --bhdump -o .\bloodhound-output`

I'm getting the below output and error message:

```
Loading cache from disk
Loaded cache with stats: 291425 ID to type mappings.
 291425 name to SID mappings.

-------------
Gathering AD data

Unhandled Exception: System.Xml.XmlException: ', hexadecimal value 0x08, is an invalid character. Line 20068, position 77.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.Throw(Int32 pos, String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseNumericCharRefInline(Int32 startPos, Boolean expand, StringBuilder internalSubsetBuilder, Int32& charCount, EntityType& entityType)
   at System.Xml.XmlTextReaderImpl.ParseCharRefInline(Int32 startPos, Int32& charCount, EntityType& entityType)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at SOAPHound.ADWS.ADWSConnector.Enumerate(String ldapBase, String ldapFilter, List`1 properties, Int32 batchSize) in C:\Users\USER\Downloads\SOAPHound-main\ADWS\ADWSConnector.cs:line 181
   at SOAPHound.ADWSUtils.GetObjects(String label) in C:\Users\USER\Downloads\SOAPHound-main\ADWSUtils.cs:line 114
   at SOAPHound.Program.ADDump() in C:\Users\USER\Downloads\SOAPHound-main\Program.cs:line 395
   at SOAPHound.Program.Run(String Server, Int32 Port, NetworkCredential Credential) in C:\Users\USER\Downloads\SOAPHound-main\Program.cs:line 279
   at SOAPHound.Program.RunOptions(Options options) in C:\Users\USER\Downloads\SOAPHound-main\Program.cs:line 246
   at SOAPHound.Program.<>c__DisplayClass24_0.<ParseCommandLineArgs>b__1(Options options) in C:\Users\USER\Downloads\SOAPHound-main\Program.cs:line 74
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at SOAPHound.Program.ParseCommandLineArgs(String[] args) in C:\Users\USER\Downloads\SOAPHound-main\Program.cs:line 73
   at SOAPHound.Program.Main(String[] args) in C:\Users\USER\Downloads\SOAPHound-main\Program.cs:line 44
```

**Comment by 0xFF-NK** [comment]
Thanks for your feedback. 

It should be fixed now, can you please check and let us know?

**Comment by doubley612** [comment]
It works, however there's a new issue:
The process takes more and more memory until it crashes (I was executing against a relatively small domain in a test env)
![image](https://github.com/FalconForceTeam/SOAPHound/assets/51437361/07170930-6019-4d04-a669-4eb0e309e3d4)

**Comment by 0xFF-NK** [comment]
Thanks, we will close the initial issue. 

For the memory crash: you can either use the autosplit function or build for x64 (instead of "any cpu"), which can use more than 4GB of RAM.
