### ISSUE TITLE
Unhandled Exception: System.ArgumentOutOfRangeException: Not a valid Win32 FileTime.

### ISSUE THREAD

**Issue by intercpt** [FalconForceTeam/SOAPHound#6]
Amazing tool, thanks for making it public :)

When I run SH to dump bloodhound data

**SOAPHound.exe SOAPHound.exe --dc 10.XX.XX.XX --cachefilename C:\Temp\XX\soapcache.txt --bhdump --domain XXXX.com -o C:\Temp\Bloodhound --autosplit --threshold 1000**

I get below error

```
Gathering split letter: c
-------------
Gathering autosplit data: (cn=ca*)

Unhandled Exception: System.ArgumentOutOfRangeException: Not a valid Win32 FileTime.
Parameter name: fileTime
   at System.DateTime.FromFileTimeUtc(Int64 fileTime)
   at System.DateTime.FromFileTime(Int64 fileTime)
   at SOAPHound.ADWS.ADWSConnector.ExtractADObjectsFromResponse(XDocument pullResponse) in C:\Users\IEUser\Downloads\SOAPHound-main\SOAPHound-main\ADWS\ADWSConnector.cs:line 376
   at SOAPHound.ADWS.ADWSConnector.Enumerate(String ldapBase, String ldapFilter, List`1 properties, Int32 batchSize) in C:\Users\IEUser\Downloads\SOAPHound-main\SOAPHound-main\ADWS\ADWSConnector.cs:line 191
   at SOAPHound.ADWSUtils.GetObjects(String label) in C:\Users\IEUser\Downloads\SOAPHound-main\SOAPHound-main\ADWSUtils.cs:line 114
   at SOAPHound.Program.ParseAutosplitObjects(String str1, String str2) in C:\Users\IEUser\Downloads\SOAPHound-main\SOAPHound-main\Program.cs:line 531
   at SOAPHound.Program.AutoSplit() in C:\Users\IEUser\Downloads\SOAPHound-main\SOAPHound-main\Program.cs:line 517
   at SOAPHound.Program.ADDump() in C:\Users\IEUser\Downloads\SOAPHound-main\SOAPHound-main\Program.cs:line 390
   at SOAPHound.Program.Run(String Server, Int32 Port, NetworkCredential Credential) in C:\Users\IEUser\Downloads\SOAPHound-main\SOAPHound-main\Program.cs:line 279
   at SOAPHound.Program.RunOptions(Options options) in C:\Users\IEUser\Downloads\SOAPHound-main\SOAPHound-main\Program.cs:line 246
   at SOAPHound.Program.<>c__DisplayClass24_0.<ParseCommandLineArgs>b__1(Options options) in C:\Users\IEUser\Downloads\SOAPHound-main\SOAPHound-main\Program.cs:line 74
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at SOAPHound.Program.ParseCommandLineArgs(String[] args) in C:\Users\IEUser\Downloads\SOAPHound-main\SOAPHound-main\Program.cs:line 73
   at SOAPHound.Program.Main(String[] args) in C:\Users\IEUser\Downloads\SOAPHound-main\SOAPHound-main\Program.cs:line 44
```

**Comment by 0xFF-NK** [comment]
Thanks for your feedback. 

It should be fixed now, can you please check and let us know?

**Comment by intercpt** [comment]
Works perfect now, thank you!
